version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-app-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://localhost:3001
      - REACT_APP_USE_MOCK=false
    networks:
      - patient-app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mock API Service
  api:
    build:
      context: ./deployment/mock-api
      dockerfile: Dockerfile
    container_name: patient-app-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-test-environment-jwt-secret}
    networks:
      - patient-app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  patient-app-network:
    driver: bridge